=== ExtraHop/behaviortransparency/schemas/bill.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "properties": {
        "spec_version": {
            "type": "string",
            "description": "The specification version this Bill of Behavior was authored against.",
            "enum": ["0.1"]
        },
        "software_name": {
            "type": "string",
            "description": "The human-readable name of the software. This should not include the vendor name."
        },
        "software_version": {
            "type": "string",
            "description": "The version of the software whose behavior is proscribed by this manifest."
        },
        "vendor_name": {
            "type": "string",
            "description": "The human-readable name of the software vendor. This is the entity who would know all the behaviors the software can perform."
        },
        "vendor_url": {
            "description": "The homepage of the software vendor.",
            "$ref": "#/definitions/url_web"
        },
        "is_exhaustive": {
            "type": "boolean",
            "description": "This bill describes ALL the behaviors of the software expressible through the bill of behavior format. Security products MAY block or prevent any behavior that is omitted from this document."
        },
        "external_references": {
            "description": "Links or IDs for more information about this software in other systems.",
            "type": "array",
            "items": { "$ref": "#/definitions/external_reference" }
        },
        "behaviors": {
            "description": "The behaviors that this software may perform in normal operation.",
            "type": "array",
            "items": { "$ref": "#/definitions/behavior" }
        }
    },
    "required": ["spec_version", "software_name", "vendor_name"],
    "additionalProperties": false,
    "definitions": {
        "behavior": {
            "properties": {
                "purpose": {
                    "type": "string",
                    "description": "A human-readable explanation of why the software performs this behavior."
                },
                "documentation_url": {
                    "description": "A link to product documentation explaining this behavior.",
                    "$ref": "#/definitions/url_web"
                }
            },
            "oneOf": [
                { "$ref": "#/definitions/behavior_external_connection" },
                { "$ref": "#/definitions/behavior_network_scan" }
            ],
            "required": ["type"]
        },
        "behavior_external_connection": {
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["external_connection"]
                },
                "ipaddr": {
                    "type": "string",
                    "description": "An IPv4 or IPv6 address or CIDR block."
                },
                "port": { "$ref": "#/definitions/port_number" },
                "domain": {
                    "type": "string",
                    "description": "A domain name. Wildcards are permitted; more advanced patterns are not allowed."
                },
                "protocol": {
                    "type": "string",
                    "description": "A lowercase IANA protocol identifier."
                },
                "cloud_provider": {
                    "$ref": "#/definitions/cloud_provider"
                }
            }
        },
        "behavior_network_scan": {
            "description": "The software will scan its local network.",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["network_scan"]
                },
                "port": { "$ref": "#/definitions/port_number" }
            }
        },
        "cloud_provider": {
            "oneOf": [
                { "$ref": "#/definitions/cloud_provider_id" },
                {
                    "type": "object",
                    "properties": {
                        "id": { "$ref": "#/definitions/cloud_provider_id" },
                        "region": {
                            "type": "string",
                            "description": "The cloud-provider-assigned region moniker, e.g. `ap-southeast-2`"
                        }
                    },
                    "required": ["id"]
                }
            ]
        },
        "cloud_provider_id": {
            "description": "Public cloud providers",
            "type": "string",
            "enum": [
                "amazon-aws",
                "google-cloud",
                "microsoft-azure",
                "oracle-cloud"
            ]
        },
        "external_reference": {
            "properties": {
                "description": {
                    "type": "string",
                    "description": "A human-readable explanation of this reference's relationship to the bill of behavior."
                },
                "source_name": {
                    "type": "string",
                    "description": "The issuing authority of the external ID.",
                    "examples": ["dodin-apl", "fedramp", "windows-pfn", "stix"]
                }
            },
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "An absolute URL"
                        }
                    },
                    "required": ["url"]
                },
                {
                    "type": "object",
                    "properties": {
                        "external_id": {
                            "type": "string",
                            "description": "The ID of this software in the system identified by source_name."
                        }
                    },
                    "dependencies": {
                        "external_id": ["source_name"]
                    }
                }
            ]
        },
        "port_number": {
            "type": "number",
            "minimum": 1,
            "maximum": 65535,
            "description": "A port number"
        },
        "url_web": {
            "type": "string",
            "description": "An absolute HTTP/S URL",
            "pattern": "^http(s)?://"
        }
    }
}

=== ExtraHop/behaviortransparency/bills/extrahop/revealx/version-8.4.0.bill.json
{
    "spec_version": "0.1",
    "software_name": "Reveal(x)",
    "vendor_name": "ExtraHop",
    "vendor_url": "https://extrahop.com",
    "is_exhaustive": true,
    "external_references": [
        {
            "url": "https://docs.extrahop.com/8.4",
            "description": "Product documentation"
        }
    ],
    "behaviors": [
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Services (US)",
            "domain": "pdx.hopcloud.extrahop.com",
            "ipaddr": "35.161.154.247/30",
            "port": 443,
            "protocol": "tcp",
            "cloud_provider": {
                "id": "amazon-aws",
                "region": "us-west-2"
            }
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Services (EU)",
            "domain": "fra.hopcloud.extrahop.com",
            "ipaddr": "52.59.110.168",
            "port": 443,
            "protocol": "tcp",
            "cloud_provider": {
                "id": "amazon-aws",
                "region": "eu-central-1"
            }
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Services (AU)",
            "domain": "syd.hopcloud.extrahop.com",
            "ipaddr": "54.66.242.25",
            "port": 443,
            "protocol": "tcp",
            "cloud_provider": {
                "id": "amazon-aws",
                "region": "ap-southeast-2"
            }
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Recordstore",
            "domain": "bigquery.googleapis.com",
            "port": 443,
            "protocol": "tcp",
            "cloud_provider": "google-cloud"
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Recordstore",
            "domain": "oauth2.googleapis.com",
            "port": 443,
            "protocol": "tcp"
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Recordstore",
            "domain": "www.googleapis.com",
            "port": 443,
            "protocol": "tcp"
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Recordstore",
            "domain": "www.mtls.googleapis.com",
            "port": 443,
            "protocol": "tcp"
        },
        {
            "type": "external_connection",
            "purpose": "ExtraHop Cloud Recordstore",
            "domain": "iamcredentials.googleapis.com",
            "port": 443,
            "protocol": "tcp"
        },
        {
            "purpose": "Find other ExtraHop appliances",
            "documentation_url": "https://docs.extrahop.com/example",
            "type": "network_scan",
            "port": 1500
        }
    ]
}

=== ExtraHop/behaviortransparency/samples/bills/acme/tax_pro/version-1.0.0.bill.json
{
    "spec_version": "0.1",
    "vendor_name": "Acme",
    "software_name": "Tax Pro",
    "software_version": "1.0.0",
    "is_exhaustive": true,
    "vendor_url": "https://acme-corp.com",
    "behaviors": [
        {
            "type": "external_connection",
            "purpose": "Save tax information",
            "domain": "api.tax-pro.acme-corp.com",
            "port": 443,
            "cloud_provider": "microsoft-azure"
        },
        {
            "type": "external_connection",
            "purpose": "Get payroll information from BCD",
            "domain": "workforcesoon.bcd.com",
            "port": 443
        },
        {
            "type": "external_connection",
            "purpose": "Collect usage and crash information",
            "documentation_url": "https://acme-corp.com/taxpro/telemetry",
            "domain": "api.appcenter.ms",
            "port": 443
        }
    ]
}
